name: Deploy to GitHub Pages
# Toggle deployment run to bypass GitHub deployment timeout


on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare Files
        run: |
          mkdir _site
          cp index.html _site/
          cp java.html _site/
          cp python.html _site/
          cp ai.html _site/
          if [ -f .nojekyll ]; then cp .nojekyll _site/; fi

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
